services: #Cada servei és un container independent.
  backend:
    build: ./backend #construeix la imatge a partir del Dockerfile
    container_name: backend
    ports:
      - "8000:8000" #port 8000 del pc està connectat  al port 80000 del docker
    command: npm run dev # comanda que executarà
    volumes: #hot-reload (els canvis locals es reflecteixen al container)
      - ./backend:/app #el codi del PC reemplaça el codi del container (hot-reload possible)
      - /app/node_modules #evita que node_modules local sobrescrigui els del container (evita conflictes) (si no, Docker sobreescriuria els node_modules del container amb el que hi hagi a la carpeta local)
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend/A-GO
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    command: npm run dev # comanda que executarà
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  db:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: exemple
    volumes:
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"